#ifndef SRC_ZHANGHONG_SRC_00152_MAXIMUM_PRODUCT_SUBARRAY_00152_MAXIMUM_PRODUCT_SUBARRAY_H_
#define SRC_ZHANGHONG_SRC_00152_MAXIMUM_PRODUCT_SUBARRAY_00152_MAXIMUM_PRODUCT_SUBARRAY_H_

#include <vector>

using namespace std;

class Solution {
public:
    int maxProduct(const vector<int>& nums);
};



#endif /* SRC_ZHANGHONG_SRC_00152_MAXIMUM_PRODUCT_SUBARRAY_00152_MAXIMUM_PRODUCT_SUBARRAY_H_ */
