#ifndef SRC_ZHANGHONG_SRC_00010_REGULAR_EXPRESSION_MATCHING_00010_REGULAR_EXPRESSION_MATCHING_H_
#define SRC_ZHANGHONG_SRC_00010_REGULAR_EXPRESSION_MATCHING_00010_REGULAR_EXPRESSION_MATCHING_H_

#include <string>
using namespace std;

namespace Solution10 {

class Solution {
public:
    bool isMatch(string s, string p);
};

}



#endif /* SRC_ZHANGHONG_SRC_00010_REGULAR_EXPRESSION_MATCHING_00010_REGULAR_EXPRESSION_MATCHING_H_ */
