#ifndef SRC_ZHANGHONG_SRC_00122_BEST_TIME_TO_BUY_AND_SELL_STOCK_2_00122_BEST_TIME_TO_BUY_AND_SELL_STOCK_2_H_
#define SRC_ZHANGHONG_SRC_00122_BEST_TIME_TO_BUY_AND_SELL_STOCK_2_00122_BEST_TIME_TO_BUY_AND_SELL_STOCK_2_H_

#include <vector>
using namespace std;

class Solution {
public:
    int maxProfit(const vector<int>& prices);
};



#endif /* SRC_ZHANGHONG_SRC_00122_BEST_TIME_TO_BUY_AND_SELL_STOCK_2_00122_BEST_TIME_TO_BUY_AND_SELL_STOCK_2_H_ */
